### ISSUE TITLE
Boot up delay should use ansible's wait_for_connection

### ISSUE THREAD

**Issue by mandoonandy** [shakenfist/deploy#56]
Just saw Jack's playbook. We should copy this bit.
```
- name: Wait 120 seconds for VM to boot
  wait_for_connection:
    delay: 10
    timeout: 120
```
